In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("Train.csv", low_memory = False)
df

,Unnamed..0,Flow.ID,Source.IP,Source.Port,Destination.IP,Destination.Port,Protocol,Timestamp,Flow.Duration,Total.Fwd.Packets,...,Active.Std,Active.Max,Active.Min,Idle.Mean,Idle.Std,Idle.Max,Idle.Min,SimillarHTTP,Inbound,Label
0,1110,172.16.0.5-192.168.50.1-872-45984-17,172.16.0.5,872,192.168.50.1,45984,17,29:44.0,2,2,...,0.0,0,0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
1,25998,172.16.0.5-192.168.50.1-867-39632-17,172.16.0.5,867,192.168.50.1,39632,17,31:01.1,43,2,...,0.0,0,0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
2,10751,172.16.0.5-192.168.50.1-818-826-17,172.16.0.5,818,192.168.50.1,826,17,24:38.4,1,2,...,0.0,0,0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
3,15983,172.16.0.5-192.168.50.1-894-32984-17,172.16.0.5,894,192.168.50.1,32984,17,27:01.5,1,2,...,0.0,0,0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
4,29733,172.16.0.5-192.168.50.1-877-12571-17,172.16.0.5,877,192.168.50.1,12571,17,26:58.1,3,2,...,0.0,0,0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359995,10503,173.194.68.109-192.168.50.9-465-58956-6,192.168.50.9,58956,173.194.68.109,465,6,24:16.5,53520,1,...,0.0,0,0,0.0,0.0,0.0,0.0,0,0,BENIGN
359996,14271,173.241.242.143-192.168.50.9-443-54494-6,192.168.50.9,54494,173.241.242.143,443,6,44:45.7,527,2,...,0.0,0,0,0.0,0.0,0.0,0.0,0,0,BENIGN
359997,4911,192.168.50.6-74.208.236.171-56713-80-6,192.168.50.6,56713,74.208.236.171,80,6,43:48.2,15817689,16,...,0.0,840296,840296,9989946.0,0.0,9989946.0,9989946.0,en.drshno.com/wp-content/themes/enfold/js/avia...,0,BENIGN
359998,249414,172.217.12.195-192.168.50.8-443-60907-6,172.217.12.195,443,192.168.50.8,60907,6,45:49.1,168,1,...,0.0,0,0,0.0,0.0,0.0,0.0,0,1,BENIGN
359999,411419,192.168.50.8-4.2.2.4-52034-53-17,192.168.50.8,52034,4.2.2.4,53,17,39:37.5,21259,2,...,0.0,0,0,0.0,0.0,0.0,0.0,0,0,BENIGN

In [3]:
df.head()

,Unnamed..0,Flow.ID,Source.IP,Source.Port,Destination.IP,Destination.Port,Protocol,Timestamp,Flow.Duration,Total.Fwd.Packets,...,Active.Std,Active.Max,Active.Min,Idle.Mean,Idle.Std,Idle.Max,Idle.Min,SimillarHTTP,Inbound,Label
0,1110,172.16.0.5-192.168.50.1-872-45984-17,172.16.0.5,872,192.168.50.1,45984,17,29:44.0,2,2,...,0.0,0,0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
1,25998,172.16.0.5-192.168.50.1-867-39632-17,172.16.0.5,867,192.168.50.1,39632,17,31:01.1,43,2,...,0.0,0,0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
2,10751,172.16.0.5-192.168.50.1-818-826-17,172.16.0.5,818,192.168.50.1,826,17,24:38.4,1,2,...,0.0,0,0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
3,15983,172.16.0.5-192.168.50.1-894-32984-17,172.16.0.5,894,192.168.50.1,32984,17,27:01.5,1,2,...,0.0,0,0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
4,29733,172.16.0.5-192.168.50.1-877-12571-17,172.16.0.5,877,192.168.50.1,12571,17,26:58.1,3,2,...,0.0,0,0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP

In [4]:
df.Label.unique()

array(['DrDoS_LDAP', 'DrDoS_DNS', 'DrDoS_MSSQL', 'DrDoS_UDP',
       'DrDoS_NetBIOS', 'Syn', 'UDP-lag', 'DrDoS_SSDP', 'DrDoS_SNMP',
       'DrDoS_NTP', 'TFTP', 'BENIGN'], dtype=object)

In [5]:

df1 = df.replace(to_replace ="DrDoS_LDAP", 
                 value =1.0) 
df2 = df1.replace(to_replace ="DrDoS_DNS", 
                 value =1.0)
df3 = df2.replace(to_replace ="DrDoS_MSSQL", 
                 value =1.0)
df4 = df3.replace(to_replace ="DrDoS_UDP", 
                 value =1.0)
df5 = df4.replace(to_replace ="DrDoS_NetBIOS", 
                 value =1.0)
df6 = df5.replace(to_replace ="Syn", 
                 value =1.0)
df7 = df6.replace(to_replace ="UDP-lag", 
                 value =1.0)
df8 = df7.replace(to_replace ="DrDoS_SSDP", 
                 value =1.0)
df9 = df8.replace(to_replace ="DrDoS_SNMP", 
                 value =1.0)
df10 = df9.replace(to_replace ="DrDoS_NTP", 
                 value =1.0)
df11 = df10.replace(to_replace ="TFTP", 
                 value =1.0)
df12 = df11.replace(to_replace ="BENIGN", 
                 value =0.0)

In [6]:
df12.Label.unique()

array([1., 0.])

In [7]:

df12["Flow.ID"] = df12["Flow.ID"].str.replace(r'\D', '')
df12["Source.IP"] = df12["Source.IP"].str.replace(r'\D', '')
df12["Destination.IP"] = df12["Destination.IP"].str.replace(r'\D', '')
df12["Timestamp"] = df12["Timestamp"].str.replace(r'\D', '')
df13 = df12.drop(columns=['SimillarHTTP'])
df14 =  df13.replace([np.inf, -np.inf], np.nan)
df15 = df14.fillna(0)

In [8]:

df15

,Unnamed..0,Flow.ID,Source.IP,Source.Port,Destination.IP,Destination.Port,Protocol,Timestamp,Flow.Duration,Total.Fwd.Packets,...,Active.Mean,Active.Std,Active.Max,Active.Min,Idle.Mean,Idle.Std,Idle.Max,Idle.Min,Inbound,Label
0,1110,17216051921685018724598417,1721605,872,192168501,45984,17,29440,2,2,...,0.0,0.0,0,0,0.0,0.0,0.0,0.0,1,1.0
1,25998,17216051921685018673963217,1721605,867,192168501,39632,17,31011,43,2,...,0.0,0.0,0,0,0.0,0.0,0.0,0.0,1,1.0
2,10751,172160519216850181882617,1721605,818,192168501,826,17,24384,1,2,...,0.0,0.0,0,0,0.0,0.0,0.0,0.0,1,1.0
3,15983,17216051921685018943298417,1721605,894,192168501,32984,17,27015,1,2,...,0.0,0.0,0,0,0.0,0.0,0.0,0.0,1,1.0
4,29733,17216051921685018771257117,1721605,877,192168501,12571,17,26581,3,2,...,0.0,0.0,0,0,0.0,0.0,0.0,0.0,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359995,10503,17319468109192168509465589566,192168509,58956,17319468109,465,6,24165,53520,1,...,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0,0.0
359996,14271,173241242143192168509443544946,192168509,54494,173241242143,443,6,44457,527,2,...,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0,0.0
359997,4911,1921685067420823617156713806,192168506,56713,74208236171,80,6,43482,15817689,16,...,840296.0,0.0,840296,840296,9989946.0,0.0,9989946.0,9989946.0,0,0.0
359998,249414,17221712195192168508443609076,17221712195,443,192168508,60907,6,45491,168,1,...,0.0,0.0,0,0,0.0,0.0,0.0,0.0,1,0.0
359999,411419,1921685084224520345317,192168508,52034,4224,53,17,39375,21259,2,...,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0,0.0

In [9]:
df15.isnull().values.any()

False

In [10]:
X = df15.drop('Label', axis=1)
y = df15['Label']

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [12]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors = 535 )
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=535)

In [13]:
y_pred = model.predict(X_test)

In [30]:
y_pred

array([1., 1., 1., ..., 0., 1., 1.])

In [32]:
X_test

,Unnamed..0,Flow.ID,Source.IP,Source.Port,Destination.IP,Destination.Port,Protocol,Timestamp,Flow.Duration,Total.Fwd.Packets,...,min_seg_size_forward,Active.Mean,Active.Std,Active.Max,Active.Min,Idle.Mean,Idle.Std,Idle.Max,Idle.Min,Inbound
190063,213024,172160519216850151967624836,1721605,51967,192168501,62483,6,30284,1,2,...,20,0.0,0.0,0,0,0.0,0.000,0.0,0.0,1
181111,198249,17216051921685012433635116,1721605,24336,192168501,3511,6,29469,1,2,...,20,0.0,0.0,0,0,0.0,0.000,0.0,0.0,1
72790,84630,1721605192168501500061937517,1721605,50006,192168501,19375,17,37439,1,2,...,0,0.0,0.0,0,0,0.0,0.000,0.0,0.0,1
152543,180979,172160519216850132293322936,1721605,32293,192168501,32293,6,30310,104329318,12,...,20,12.5,23.0,47,1,20865853.4,5649509.788,26235961.0,12915619.0,1
250452,37225,17216051921685018915566517,1721605,891,192168501,55665,17,22435,2,2,...,0,0.0,0.0,0,0,0.0,0.000,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286905,59,1721605192168501648641117,1721605,648,192168501,6411,17,38422,806,10,...,8,0.0,0.0,0,0,0.0,0.000,0.0,0.0,1
154229,427507,172160519216850139149476246,1721605,39149,192168501,47624,6,32308,1,2,...,20,0.0,0.0,0,0,0.0,0.000,0.0,0.0,1
345475,81940,17221712194192168506443573476,17221712194,443,192168506,57347,6,41050,173,1,...,20,0.0,0.0,0,0,0.0,0.000,0.0,0.0,1
126127,105146,17216051921685018823919117,1721605,882,192168501,39191,17,00001,1,2,...,229,0.0,0.0,0,0,0.0,0.000,0.0,0.0,1
264003,24150,17216051921685016932971417,1721605,693,192168501,29714,17,17353,2,2,...,14,0.0,0.0,0,0,0.0,0.000,0.0,0.0,1

In [14]:

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 5946    71]
 [   18 65965]]
              precision    recall  f1-score   support

         0.0       1.00      0.99      0.99      6017
         1.0       1.00      1.00      1.00     65983

    accuracy                           1.00     72000
   macro avg       1.00      0.99      1.00     72000
weighted avg       1.00      1.00      1.00     72000

In [18]:
!pip3 install mlxtend
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
model2 = KNeighborsClassifier(n_neighbors = 537 )
sfs = SFS(model2,
          k_features=86,
          forward=True,
          floating=False,
          scoring = 'r2',
          cv = 0)

Requirement already satisfied: mlxtend in c:\users\lundu\anaconda3\lib\site-packages (0.18.0)
Requirement already satisfied: pandas>=0.24.2 in c:\users\lundu\anaconda3\lib\site-packages (from mlxtend) (1.1.3)
Requirement already satisfied: numpy>=1.16.2 in c:\users\lundu\anaconda3\lib\site-packages (from mlxtend) (1.19.2)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\lundu\anaconda3\lib\site-packages (from mlxtend) (0.23.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\lundu\anaconda3\lib\site-packages (from mlxtend) (0.17.0)
Requirement already satisfied: setuptools in c:\users\lundu\anaconda3\lib\site-packages (from mlxtend) (50.3.1.post20201107)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\lundu\anaconda3\lib\site-packages (from mlxtend) (3.3.2)
Requirement already satisfied: scipy>=1.2.1 in c:\users\lundu\anaconda3\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: pytz>=2017.2 in c:\users\lundu\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\lundu\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2.8.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\lundu\anaconda3\lib\site-packages (from scikit-learn>=0.20.3->mlxtend) (2.1.0)
Requirement already satisfied: certifi>=2020.06.20 in c:\users\lundu\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2020.6.20)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\lundu\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\lundu\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\lundu\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in c:\users\lundu\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (8.0.1)
Requirement already satisfied: six>=1.5 in c:\users\lundu\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.24.2->mlxtend) (1.15.0)

In [ ]:
sfs.fit(X,y)

In [17]:
X.shape[1]

86